language: node_js
node_js: node
cache: yarn
before_install:
  - npm install -g yarn
install:
  - yarn global add codecov
  - yarn
  - cypress install
script:
  - yarn test
  - yarn cy:run
  - codecov
