language: node_js
node_js: node
cache: yarn
addons:
  chrome: stable
before_install:
  - npm install -g yarn
install:
  - yarn global add codecov
  - yarn
  - cypress install
script:
  - yarn test
  - yarn cy:run
  - cypress run --headless --browser chrome
  - cypress run --headless --browser firefox
  - codecov
