const fs = require('fs')
const pkg = JSON.parse(fs.readFileSync('package.json', 'utf8'))
const readline = require('readline')
const buffer = []
const bufferReadme = []
const githubUsername = new URL(pkg.homepage).pathname.split('/')[1]
const pkgNameUCFirst = pkg.name.charAt(0).toUpperCase() + pkg.name.slice(1)

//
// Demo
//
const searchObjects = [
  {
    search: '<title>',
    replace: pkgNameUCFirst + '</title>',
  },
  {
    search: '<script src="dist/',
    replace: pkg.name + '.js"></script>',
  },
  {
    search: '/* global Vue, Quasar, animatable, ',
    replace: pkg.outputName + ' */',
  },
  {
    search: 'const animationsSet = ',
    replace: pkg.outputName,
  },
  {
    search: "this.packageName = '",
    replace: pkg.name + "'",
  },
  {
    search: "this.githubUsername = '",
    replace: githubUsername + "'",
  },
]

async function processLineByLine() {
  const fileStream = fs.createReadStream('index.html')

  const rl = readline.createInterface({
    input: fileStream,
    crlfDelay: Infinity,
  })

  for await (let line of rl) {
    searchObjects.forEach((obj) => {
      const substr = line.indexOf(obj.search)
      if (substr >= 0) {
        line = line.substring(0, substr + obj.search.length) + obj.replace
      }
    })
    buffer.push(line)
  }

  fileStream.once('close', () => {
    const stream = fs.createWriteStream('index.html')
    stream.once('open', () => {
      buffer.forEach((key) => {
        stream.write(`${key}\n`)
      })
      stream.end()
    })
  })
}

processLineByLine()

//
// README
//
const searchObjectsReadme = ['githubUsername', 'pkg.name', 'pkgNameUCFirst', 'pkg.outputName']
async function processLineByLineReadme() {
  bufferReadme.push(`[//]: # 'DO NOT EDIT THIS FILE!'`)
  bufferReadme.push(`[//]: # 'This file is auto generated. Edit README.template.md and then use \`yarn gen\`'`)
  bufferReadme.push('')
  const fileStream = fs.createReadStream('README.template.md')

  const rl = readline.createInterface({
    input: fileStream,
    crlfDelay: Infinity,
  })

  for await (let line of rl) {
    searchObjectsReadme.forEach((obj) => {
      const substr = line.indexOf(`{{${obj}}}`)
      if (substr >= 0) {
        const regex = new RegExp(`{{${obj}}}`, 'g')
        line = line.replace(regex, eval(obj))
      }
    })
    bufferReadme.push(line)
  }

  fileStream.once('close', () => {
    const stream = fs.createWriteStream('README.md')
    stream.once('open', () => {
      bufferReadme.forEach((key) => {
        stream.write(`${key}\n`)
      })
      stream.end()
    })
  })
}

processLineByLineReadme()
